name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: "[${{matrix.otp}}/${{matrix.elixir}}, ${{matrix.rust}}] CI Tests"
    strategy:
      matrix:
        otp: [24, 25]
        elixir: ["1.14.4"]
        rust: ["stable", "nightly"]
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{matrix.rust}}
          override: true

      - name: rust-cache
        uses: Swatinem/rust-cache@v1
        id: rust-cache
        with:
          working-directory: ./native/xairo
          target-dir: ./native/xairo/target
          key: rs-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ matrix.rust }}-${{ hashFiles('Cargo.lock') }}

      - name: mix-cache
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - name: cargo build
        run: cargo build
        working-directory: ./native/xairo
        if: steps.rust-cache.outputs.cache-hit != 'true'

      - name: mix local
        run: |
          mix local.rebar --force
          mix local.hex --force

      - name: mix compile
        run: |
          mix deps.get
          mix deps.compile
          mix compile
        if: steps.mix-cache.outputs.cache-hit != 'true'

      - name: mix checks
        run: |
          mix deps.unlock --check-unused
          mix format --check-formatted

      - name: mix test
        run: mix test
